name: GitHub integration testops

on:
  workflow_dispatch:
    inputs:
      TEST_ENDPOINT:
        description: "Endpoint for tests"
        required: true
        default: https://dev.github.com
      TEST_BROWSER:
        description: "Browser for tests"
        required: true
        default: chrome
      ALLURE_JOB_RUN_ID:
        description: "ALLURE_JOB_RUN_ID service parameter. Leave blank."
        required: false
      ALLURE_USERNAME:
        description: "ALLURE_USERNAME service parameter. Leave blank"
        required: false

env:
  ALLURE_RESULTS: "build/allure-results"
  ALLURE_JOB_RUN_ID: ${{ github.event.inputs.ALLURE_JOB_RUN_ID }}

jobs:
  all-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 21
        id: setup-java
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin
      - name: install and configure allurectl
        uses: allure-framework/setup-allurectl@v1.0.0
        with:
          allure-endpoint: https://demo.testops.cloud
          allure-token: ${{ secrets.ALLURE_TOKEN }}
          allure-project-id: 338
          allurectl-version: 2.18.0
      - name: Build with Gradle and upload test results to TestOps
        run: |
          allurectl watch -- ./gradlew clean test
          export $( allurectl job-run env)
          printenv | grep ALLURE_
          printenv | grep TEST_
        env:
          TEST_ENDPOINT: ${{ github.event.inputs.TEST_ENDPOINT }}
          TEST_BROWSER: ${{ github.event.inputs.TEST_BROWSER }}
          JAVA_HOME: ${{ steps.setup-java.outputs.path }}
          
